### ISSUE TITLE
bam2fastq module

### ISSUE THREAD

**Issue by whelena** [LCR-BCCRC/lcr-modules#10]

**Comment by BrunoGrandePhD** [comment]
I and others have had mixed experience with `picard SamToFastq`. I would be curious to hear if people have consistently been able to use it without issues in the LCR. 

Alternatively, I have a script that I've been using (mostly with GSC BAM files) that uses `samtools fastq` instead. I haven't used it on genome BAM files, so I would need to confirm if its memory usage is reasonable (or at least as reasonable as Picard). 

When I was research BAM-to-FASTQ conversion, I came across these links. I'm posting them here mostly as a note for myself if I end up tackling this module. 

https://bioinformatics.stackexchange.com/questions/8938/convert-bam-to-properly-paired-fastq-files
https://github.com/samtools/samtools/issues/874
