### ISSUE TITLE
GRIDSS not working for hs37d5 reference

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#104]
I tried to launch this on an ICGC genome and get the following error:
```
Building DAG of jobs...
Executing subworkflow reference_files.
Building DAG of jobs...
MissingRuleException:
No rule to produce genomes/hs37d5/encode/encode-blacklist.hs37d5.bed (if you use input functions make sure that they don't raise unexpected exceptions).
```

I also tried pointing to the development reference directory but it fails due to permissions error:

```
PermissionError: [Errno 13] Permission denied: '.snakemake/log'
```

@lkhilton this might be fixed by opening up permissions in that directory.

**Comment by rdmorin** [comment]
I realized that switching to version 2.4 solves the first problem.

**Comment by lkhilton** [comment]
Is the second problem also solved?

**Comment by rdmorin** [comment]
I can't test it right now because Snakemake is running. Did you change/open the permissions on that directory?

**Comment by lkhilton** [comment]
I didn't, but others have written to that directory recently, so I'm not sure why you got that error

**Comment by rdmorin** [comment]
```
drwxr-sr-x  8 lhilton morinlab_sysadmin 4.0K Jul 23 14:36 .snakemake
```
