### ISSUE TITLE
Ensure the GSC reference is used for decompression in bam2fastq module

### ISSUE THREAD

**Issue by Kdreval** [LCR-BCCRC/lcr-modules#108]
Some of the bam files are being crammed, and it was found that some of the compressed files rely on the specific reference that was used in file compression. Those samples were exiting with error in bam2fastq module. To prevent this, we need  to modify the bam2fastq module to use GSC reference for decompression.

**Comment by rdmorin** [comment]
Is this done (via the PR I just approved)? If so, please close

**Comment by Kdreval** [comment]
No, it was not done in that PR. It is still work in progress.

**Comment by rdmorin** [comment]
Closing. This actually won't be necessary because the GSC is reheadering all the RNA-seq bam files to use the proper reference. If that process doesnt fix our issue we can re-open.
