### ISSUE TITLE
Make strand a required column for LCR-modules samples table?

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#111]
In order for the Picard QC modules to work for RNA-seq, the strandedess of the libraries needs to be specified. This would need to be supplied per library in the metadata. Should we make this required so the demo can actually work with Picard QC? If so we will have to document this and update the demo.

**Comment by Kdreval** [comment]
The strandness information will also be required in kallisto module. I support that this should be required column in metadata

**Comment by lkhilton** [comment]
We probably also be incorporating read length in the samples table for e.g. STAR

**Comment by rdmorin** [comment]
Excellent point

**Comment by rdmorin** [comment]
And polyA vs ribodepletion?

**Comment by lkhilton** [comment]
Are there any modules that would behave differently based on this information?

**Comment by rdmorin** [comment]
Probably not (at least not yet). I was envisioning it could be used as a variable for any batch effect correction in level 3 analyses.

**Comment by BrunoGrandePhD** [comment]
These requirements can be added on a per-tool basis. You can add a schemas in the central repository, and symlink that schema in the `schemas/` subdirectory of the relevant modules. You can create one schema per extra required variable, or you can group them in some logical fashion.

**Comment by rdmorin** [comment]
I suppose this is closeable once we have implemented this for STAR.

**Comment by lkhilton** [comment]
Read lengths added to STAR in #119
