### ISSUE TITLE
SOBDetector

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#112]
A tool to detect strand bias of variant calls. This has been used by other groups as an important filtering criterion for removing false positives.

https://github.com/mikdio/SOBDetector

**Comment by rdmorin** [comment]
Any movement on this, @ckrushton ?

**Comment by rdmorin** [comment]
Assigning to @oncogenomics. this should be a good "first" tool for you to implement.

**Comment by Kdreval** [comment]
Will close this issue due to low interest in developing and using this tool
