### ISSUE TITLE
3d structure-based hot spot tools

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#113]
We should try out one of these and determine which one(s) should be rolled into LCR-modules

https://github.com/KarchinLab/HotMAPS
https://github.com/ding-lab/hotspot3d

Or others I might not be aware of.

**Comment by rdmorin** [comment]
Manuela has gotten some nice results from HotMAPS. I wonder if that's something we could make portable, given it's reliance on a local mysql instance. Maybe we'd need something Dockerized?

**Comment by Kdreval** [comment]
Closing this issue as completed with the hotmaps module. It was merged in PRs #301, #302, and #325
