### ISSUE TITLE
pseudoalignment modules (salmon, kallisto)

### ISSUE THREAD

**Issue by whelena** [LCR-BCCRC/lcr-modules#12]

**Comment by rdmorin** [comment]
@Kdreval has completed version 1 of the Salmon module. Kallisto is less pressing but should still be done.

**Comment by Kdreval** [comment]
There is a draft of kallisto module. Unlike, salmon, it requires the strandness information to be supplied with sample table. I will find a way to supply this information without modifying the project-wide sample tables, like `gambl_samples_available.tsv` for example.

**Comment by oncogenomics** [comment]
@rdmorin This one is done too, closed?

**Comment by rdmorin** [comment]
Kallisto isn't done

**Comment by Kdreval** [comment]
Salmon module makes the kallisto redundant, so I am closing this issue.
