### ISSUE TITLE
VCF2maf should delete intermediate vep outputs

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#120]
I noticed vcf2maf will error out if a ".vep.vcf" file from a previous run exists in the output directory. This file should be deleted at the end of a run. Since the naming is consistent, it could be marked as a tempfile so it is cleared if the pipeline fails partway through.

**Comment by lkhilton** [comment]
Are you using the latest master? I addressed this in #115.

**Comment by rdmorin** [comment]
Quite possibly not. Now that you mention it I remember this change. Note that I am wary of pulling in Master due to some edits made directly to the GAMBL "production" clone of the repo.

**Comment by rdmorin** [comment]
Indeed this was fixed before I reported it. Thanks @lkhilton !
