### ISSUE TITLE
Standardize output file names from LoFreq, Strelka and Mutect

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#121]
There are slight differences in the naming format of the final files output by these pipelines. These should be standardized so patterns can be used in level3 analyses.
LoFreq:
BLGSP-71-06-00004-01A-11D--BLGSP-71-06-00004-99A-01D--matched.combined.vcf.gz.  #.combined (no "passed")
Strelka:
BLGSP-71-06-00004-01A-11D--BLGSP-71-06-00004-99A-01D--matched_combined.passed.vcf.gz #_combined.passed
Mutect:
BLGSP-71-06-00004-01A-11D--BLGSP-71-06-00004-99A-01D--matched.output.passed.vcf.gz #.output.passed

I also noticed that non-standard chromosomes are in some of the VCF outputs from these tools (e.g. LoFreq). 

chrUn_KI270590v1 etc

Shouldn't these also be dropped?

**Comment by lkhilton** [comment]
Addressed by #124, #125, and #126.
