### ISSUE TITLE
LoFreq produces corrupted VCF lines at some positions

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#122]
There are a few rows in the LoFreq VCFs that contain a non-ACTG character in the REF column. This may relate to bases in the reference genome that are not ACTG (i.e. IUPAC ambiguity characters). 

Here's a fix that can get rid of these. 
```
awk '($4=="A" || $4 == "C" || $4=="T" || $4=="G" || /\#/)'
```

**Comment by Kdreval** [comment]
This has been addressed in the filtering script implemented in lofreq module with PR [124](https://github.com/LCR-BCCRC/lcr-modules/pull/124) so the issue can be closed.
