### ISSUE TITLE
LoFreq VCF misuse of AF

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#128]
The Lofreq somatic outputs use AF to denote variant allele frequency in the tumour. This is very problematic if we ever want to use the Gnomad VCF with AF information to annotate these VCFs. The (silent) behaviour is for 'bcftools annotate' to substitute the VAF (mis-named AF) in the lofreq VCF with the Gnomad AF. For any variants not in Gnomad, they keep the original value. In other words, common and rare variants have the population frequency stored in AF and the rest have VAF stored there. This is obviously hugely problematic. I propose an easy fix. The following perl command in a pipe from (and to) bcftools view should replace the AF with VAF in the header and every line. 

```
 perl -ne 's/AF=/VAF=/g;s/ID=AF/ID=VAF/;print;'
```

**Comment by rdmorin** [comment]
Another solution using bcftools is to drop the AF completely but there are clearly drawbacks to this. I will point out that the DP and DP4 columns can be used to regenerate the VAF if needed. My bcftools skills are not strong but I suspect there is a way to recalculate this with bcftools and add it back as a new (e.g. VAF) annotation. 

```
bcftools annotate -x INFO/AF lofreq.vcf.gz | bcftools view -O z -o lofreq.noAF.vcf.gz
bcftools index -t lofreq.noAF.vcf.gz
```

**Comment by Kdreval** [comment]
I think the first solution of renaming AF to VAF is an option to go. I will implement this together with the fix for the killed runs

**Comment by Kdreval** [comment]
This issue has been addressed with PR [# 129](https://github.com/LCR-BCCRC/lcr-modules/pull/129) and can be closed.
