### ISSUE TITLE
Battenberg seg files do not include subclonal information

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#148]
In parsing the Battenberg output and converting it to seg files for post-processing and visualization, we are currently only using the "top" clonal population. In tumours with substantial subclonal fractions, this gives very different copy number profiles than expected. We need to update cnv2igv.py to handle this properly.

**Comment by Kdreval** [comment]
submitted [PR #15](https://github.com/LCR-BCCRC/lcr-scripts/pull/15)

**Comment by Kdreval** [comment]
I will close this issue since it is addressed in version 1.3 of the cnv2igv script
