### ISSUE TITLE
Update cookiecutter to use new oncopipe features and model updated design practices

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#158]
Since the cookiecutter was made, we've adopted some conventions that we probably want to be a component of all new modules. The easiest way to encourage this is through the cookiecutter template. The ones that immediately come to mind are:

- [x] Use the new in_module option for symlinking output files
- [x] Switch all input files to use absolute symlinks instead of the default (relative)
- [x] Group the input rule with the second rule to show users how to use grouping to avoid a ton of fast local jobs
- [x] In-line comment on how to accomplish cram support (i.e. tell the user to create second symlink to .crai file in the input function)
- [x] Add the oncopipe version-checking code that was just added to the Battenberg module
- [x] Resource unpacking example (?)
- [ ] Add module's "scripts" directory to PATH environment variable (?)

**Comment by rdmorin** [comment]
@Kdreval and @lkhilton probably have other ideas for what else we could/should include

**Comment by rdmorin** [comment]
RE: Group the input rule with the second rule to show users how to use grouping to avoid a ton of fast local jobs
Has anyone else started doing this in their tools? I had some errors with this originally but my DAG was more complex than I had originally thought. Once I simplified the grouping to just pairs of rules that ran consecutively it seemed to work fine.

**Comment by Kdreval** [comment]
This is addressed in PR https://github.com/LCR-BCCRC/lcr-modules/pull/172
