### ISSUE TITLE
picard_qc module is buggy

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#168]
I spent an hour this afternoon trying to get the picard_qc v1.0 module running on my data. Currently it has problems with specifying capture bed files, it expects a "strand" column in the table regardless of whether the input data is RNAseq or capture (although "strand" is not a required column in the module schema), and it seems to have a knack for periodic wildcard expansion that made it impossible to use the `rule all` as it is currently coded. It would be great if someone could spend some time debugging this module and improving its flexibility.

**Comment by Lakshay-sethi** [comment]
Hi, 
While testing the demo, I also faced this strand issue for a number of modules.  It would be a big help if the person tacking this, could also look into other modules too.

**Comment by lkhilton** [comment]
Which other modules did you encounter the strand issue for?

**Comment by Kdreval** [comment]
New module `qc` in #237 replaces this module, so I will close this issue now.
