### ISSUE TITLE
Rainstorm/Doppler

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#21]
Python and R implementations exist. Need to consider if we should make Snakemake workflows for both or just move forward with the most useful/efficient.

**Comment by matnguyen** [comment]
The way I've been running it is Python-Rainstorm, R-Doppler (and I think this is the way Prasath ran it too)

**Comment by matnguyen** [comment]
I can't assign myself here, but @BrunoGrandePhD you can assign me to this

**Comment by Kdreval** [comment]
This was addressed in PR #183 implementing both Rainstorm and Doppler in one snakefile
