### ISSUE TITLE
Default unmatched normal bug

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#219]
The default unmatched normal checking is still looking across genome_build and seq_type values, so it thinks there is more than one matching normal ID if you try to use the same normal ID for multiple genome_build/seq_type combinations. This contradicts what is documented in the LCR-modules documentation and in the error message output by oncopipe: 
```
elif num_matches > 1:
                    print(
                    f"There are {num_matches} {seq_type} samples matching "
                    f"the normal ID {normal_id}. This means there are {num_matches} normal samples for {key} in "
                    f"the samples table and it is not desired. Please ensure all sample_id, seq_type, "
                    f"and genome_build combinations are unique."
                    )
                    quit()
``` 
Can this be patched at some point so that it only checks within a genome_build/seq_type combination?

**Comment by lkhilton** [comment]
I think it might be as simple as editing [this code](https://github.com/LCR-BCCRC/lcr-modules/blob/f046faba655c23dddf4f7fb22fe932a7ef78a9bd/oncopipe/oncopipe/__init__.py#L1243-L1244)

to: 

```
normal_row = samples[
                    (samples.sample_id == normal_id) & (samples.seq_type == seq_type) & (samples.genome_build == genome_build)
```

**Comment by Kdreval** [comment]
This is resolved in v12
