### ISSUE TITLE
STAR

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#22]
It is becoming increasingly clear to me that we need a STAR pipeline that runs it with sensible parameters. The default settings are terrible. We should generate bam files that can be run through STAR-fusion later on and that include all the original reads including:

Chimeric/discordant read pairs
Unmapped reads
No hard clipping

**Comment by lkhilton** [comment]
@BrunoGrandePhD as you develop this I wanted you to be aware of a problem I've run into with STAR's built-in sorting function. Basically it has problems with some transcriptomes, especially if there's abnormal depth in a region (I think the likely culprit here is ribosomal and/or MT transcripts that didn't get cleaned up properly), and it might not be possible to designate enough memory to solve the problem. According to this STAR GitHub [Issue](https://github.com/alexdobin/STAR/issues/870) the solution is to use samtools sort. 

Therefore it might make sense to output unsorted BAM files from STAR by default, and sort them with samtools sort. If we wanted to use samtools to also mark duplicates this could be accomplished in a single rule.

**Comment by BrunoGrandePhD** [comment]
Yeah, I ran into this too in my one test run with STAR. It did seem strange that my RNA-seq BAM needed 50 GB of RAM. Thanks for pointing out the GitHub issue! I will happily resort to using samtools or sambamba for BAM sorting.

**Comment by rdmorin** [comment]
Using Samtools sort will probably be faster too because it uses threading elegantly. Keep in mind that for any samtools sort step, you should explicitly provide the temp prefix (-T) as scratch space. This is more of a concern for files that can't be sorted in memory.

**Comment by BrunoGrandePhD** [comment]
sambamba's main draw was its parallelization, but I don't know if it's much faster now that samtools has implementing threading. I also looked into biobambam2's [bamsormadup](https://gitlab.com/german.tischler/biobambam2), which sorts and mark duplicates in one step. However, while it might be more efficient and faster, the documentation isn't great and it isn't being updated regularly on conda. I might use sambamba for its parallelized mark duplicates over Picard.

**Comment by rdmorin** [comment]
Someone out there probably has benchmarked samtools sort vs sambamba with an equal number of threads. I haven't compared them head to head but samtools is very robust. I would also prefer to avoid Picard wherever there is another reasonable option.

**Comment by BrunoGrandePhD** [comment]
Based on this blog post, sambamba makes better use of multithreading, but it's from 2016. samtools has probably improved in the interim. Since I'll be using sambamba over picard for marking duplicates, I'll use probably sambamba for sorting too. 

https://www.basepairtech.com/blog/sorting-bam-files-samtools-vs-sambamba/
