### ISSUE TITLE
RNAseq Variant Calling Pipeline

### ISSUE THREAD

**Issue by matnguyen** [LCR-BCCRC/lcr-modules#23]
I have an RNAseq Variant Calling Pipeline in snakemake form, adapted from the one made by Jeffrey for BL. I can modify it to fit lcr-modules guidelines.

**Comment by BrunoGrandePhD** [comment]
Write access granted. Please develop on a branch named after your module (_e.g._ `rnaseq-variant-calling`) and then submit a PR. I'll have more detailed contribution guidelines before the end of the week.

**Comment by Kdreval** [comment]
This module is in PR #184
