### ISSUE TITLE
Missing lymphgen script

### ISSUE THREAD

**Issue by emouts** [LCR-BCCRC/lcr-modules#255]
Hello,

Thank you for all your hard work in creating and maintaining this suite of modules, it has been a great resource!

I had a question about running the lymphgen module: The config["lcr-modules"]["lymphgen"]["options"]["lymphgen_run"]["lymphgen_path"] parameter is set to a local path in the current version ("/projects/rmorin/software/lcr-scripts/LymphGen/Run_Lymphgen.R") and I have trouble locating that script for my own run. It doesn't seem to be included in the current version of [lcr-scripts](https://github.com/LCR-BCCRC/lcr-scripts) and there is no src directory under [modules/lymphgen/1.0](https://github.com/LCR-BCCRC/lcr-modules/tree/master/modules/lymphgen/1.0). I had a look through the code to check for any downloads, but the only one that seems to be there is the [LGenIC](https://github.com/ckrushton/LGenIC) repo, which doesn't include that R script. 

Could someone please point me in the right direction? I'm aware lymphgen has a web tool but I was looking to incorporate the post-processing of the results into a snakemake pipeline, which would make manually using a web tool inconvenient.

Thanks a lot for your help!

Ilias

**Comment by rdmorin** [comment]
Thanks for pointing this out. I believe @ckrushton or @lkhilton should be able to help with this.

**Comment by lkhilton** [comment]
Hi Ilias, 

Thanks for your message, I'm glad you're finding our tools useful. Unfortunately the LymphGen source code was shared with us by George Wright and we don't have his permission to distribute it outside of our organization. I realize this limits the utility of our module for you, however I see a couple of possible ways forward for you: 

1. Set the target of the LymphGen module to be the outputs of LGenIC, then upload those files to the LymphGen web tool. 
2. Contact George Wright and ask for permission to access the source code. 

Sorry I can't be of more assistance with this. 

Laura

**Comment by rdmorin** [comment]
Can we also ask George directly if he's alright with us sharing it broadly?

**Comment by emouts** [comment]
Thank you both very much for the responses!

**Comment by nuttynutmore** [comment]
I've had a look more closely at the suggested fix from the Morin lab- I'm not happy with their LGENIC solution as it doesn't include SV data.  I think I'm going to try create our own instead (using/ upcycling some old code from when I've done this previously).

**Comment by Kdreval** [comment]
Closing this issue as inactive
