### ISSUE TITLE
Refactor modutils as a more object-oriented package

### ISSUE THREAD

**Issue by BrunoGrandePhD** [LCR-BCCRC/lcr-modules#27]
What started off as a small collection of functions has become more complex and could use a refactor now knowing what is required of modutils. The package would be much simpler if an object-oriented approach would be taken for describing modules. Here's a list of features that would be easier to implement with OOP:

- [ ] Format `{REPODIR}` and `{MODSDIR}` in formatters (_e.g._ `switch_on_*()` functions)
- [x] Use `inspect` package to pull standard variables from parent frame ([example](https://github.com/snakemake/snakemake/blob/master/snakemake/utils.py#L377-L413))
- [ ] Automatically check/store `locals()` when setting up a module and restoring `locals()` when cleaning up a module, allowing `switch_on_*()` dictionaries to be created separately. 
- [ ] Better handling of `unmatched_normal_id` and `unmatched_normals`. 
- [x] Better warning/error messages. For example, the module name should be included in the following warning:
  >Some samples have seq_types {'mirna'} that are not configured in the pairing config. They will be dropped.

**Comment by Kdreval** [comment]
Will close this for now, unsure where this is going and what to implement. Can always re-open the issue later when this becomes more urgent.
