### ISSUE TITLE
Demo doesn't dry-run as documented

### ISSUE THREAD

**Issue by Pranav-Garg** [LCR-BCCRC/lcr-modules#288]
The command `nice snakemake --dry-run --use-conda all` fails because there is no `Snakefile` in the demo directory.
I then tried `snakemake --dry-run --use-conda all -s genome_Snakefile.smk`, which also fails with:
```
InputFunctionException in rule hardlink_download in file /projects/karsanlab/pgarg_dev/software/src/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk, line 584:
Error:
  Exception:  Could not find rule to generate   genomes/ grch37 / main_chromosomes/main_chromosomes.grch37.txt  .
Wildcards:
  genome_build=grch37
  suffix=main_chromosomes/main_chromosomes.grch37.txt
Traceback:
  File "/projects/karsanlab/pgarg_dev/software/src/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk", line 475, in hardlink_same_provider
```
(the exact rule that fails above is random)

Editing the file `lcr-modules/workflows/reference_files/2.4/reference_files_header.smk`, under function `get_matching_download_rules`,
I changed 
```
rule_names = [ r for r in dir(rules) if r.startswith("download_")]
```
to 
```
rule_names = [ r for r in rules._rules.keys() if r.startswith("download_")]
```
and added 
```
file = file.replace(' ', '')
```
to the same function since whitespaces were somehow being prepended to the paths. But this also fails.
I think perhaps the developers would be better equipped to debug this issue than me.

Related to this, it would be helpful to see what directory structure and files the Reference Files Workflow generates, so that I can symlink existing downloads to it, and perhaps bypass the above issue.

**Comment by Kdreval** [comment]
Hi @Pranav-Garg ,

That's right, the Snakefile has been split into seq_type-specific workflows to better represent the real-world scenarios, and documentation has not been updated since then but is something we are planning to bring up to speed soon.

Thank you for reporting the error. Someone else also reported this issue and we are investigating. It appears that after certain version of snakemake the subworkflows are handled differently. Can you please:
1. Post the version of snakemake you have in the environment
2. Let us know if there is a Warning message printed to stdout right after you try running the snakemake command indicating that oncopipe was imported outside of snakemake.

Thanks

**Comment by Pranav-Garg** [comment]
Snakemake version: 7.32.4

Yes, there was such a warning. Full output below (I removed the full file paths):
```
Warning: The oncopipe package was imported outside of a snakefile. Most functions are designed to work within a snakefile. Some unexpected behaviour/errors might occur.
modules/slms_3/1.0/slms_3.smk:411: SyntaxWarning: invalid escape sequence '\s'
  str(rules._slms_3_annotate_strelka_gnomad.output.vcf),
modules/slms_3/1.0/slms_3.smk:438: SyntaxWarning: invalid escape sequence '\s'
  rules._starfish_all.input,
modules/slms_3/1.0/slms_3.smk:534: SyntaxWarning: invalid escape sequence '\#'
modules/slms_3/1.0/slms_3.smk:553: SyntaxWarning: invalid escape sequence '\#'
modules/slms_3/1.0/../../starfish/2.0/starfish.smk:236: SyntaxWarning: invalid escape sequence '\S'
  # Perform some clean-up tasks, including storing the module-specific
modules/pathseq/1.0/pathseq.smk:119: SyntaxWarning: invalid escape sequence '\>'
  R={input.genome_fa}
modules/pathseq/1.0/pathseq.smk:133: SyntaxWarning: invalid escape sequence '\>'
  log:
Building DAG of jobs...
Executing subworkflow reference_files.
workflows/reference_files/2.4/reference_files.smk:1460: SyntaxWarning: invalid escape sequence '\/'
workflows/reference_files/2.4/reference_files.smk:1480: SyntaxWarning: invalid escape sequence '\/'
Building DAG of jobs...
InputFunctionException in rule hardlink_download in file workflows/reference_files/2.4/reference_files_header.smk, line 584:
Error:
  Exception:  Could not find rule to generate   genomes/ grch37 / repeatmasker/repeatmasker.grch37.bed  .
Wildcards:
  genome_build=grch37
  suffix=repeatmasker/repeatmasker.grch37.bed
Traceback:
  File "workflows/reference_files/2.4/reference_files_header.smk", line 475, in hardlink_same_provider
```

**Comment by focusonskills** [comment]
Have you managed to solve the issue?
I have encountered the same problem trying to run the demo data.

**Comment by Kdreval** [comment]
Hi all,
Sorry for the delay in resolving this issue.
@focusonskills , the problem here is associated with the way new snakemake version started to handle the subworkflows, which makes the new versions incompatible with lcr-modules.
A solution is to use a locked conda environment from the following recipe: https://github.com/LCR-BCCRC/lcr-modules/blob/master/demo/env.yaml This is a copy of our production environment and it has been tested to resolve this issue on several systems and OS versions.

Please let us know if you will have any other questions.

**Comment by focusonskills** [comment]
> Hi all, Sorry for the delay in resolving this issue. @focusonskills , the problem here is associated with the way new snakemake version started to handle the subworkflows, which makes the new versions incompatible with lcr-modules. A solution is to use a locked conda environment from the following recipe: https://github.com/LCR-BCCRC/lcr-modules/blob/master/demo/env.yaml This is a copy of our production environment and it has been tested to resolve this issue on several systems and OS versions.
> 
> Please let us know if you will have any other questions.

I've tried to create a locked enviroment with conda-lock using env.yaml under the demo folder.
However I am still getting the same output as OP where it stuck at generating reference.
Which snakemake version is actually required for the modules?
I see these in the env.yaml :
  - snakemake-minimal=7.15.2
  - pip:
    - snakemake==6.13.1

**Comment by lkhilton** [comment]
When we generate the environment, `snakemake --version` returns `7.15.2`. This version should work. 
What is the output of `snakemake --version` and `pip show oncopipe` when you activate your environment? 
Can you post the output of `conda env export` from the activated environment?

**Comment by focusonskills** [comment]
> When we generate the environment, `snakemake --version` returns `7.15.2`. This version should work. What is the output of `snakemake --version` and `pip show oncopipe` when you activate your environment? Can you post the output of `conda env export` from the activated environment?

`snakemake --version` gives 7.32.4
`pip show oncopipe` gives version 1.0.12
`conda env export` gives the following.
Do you know why the snakemake version doesn't match with the one in conda enviroment?

name: opv12
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.8.3=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - async-timeout=4.0.2=py38h06a4308_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.1.0=py38h06a4308_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - bcrypt=3.2.2=py38h0a891b7_1
  - blas=1.1=openblas
  - boto3=1.24.89=pyhd8ed1ab_0
  - botocore=1.27.89=pyhd8ed1ab_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.9.24=ha878542_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.9.24=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - coincbc=2.10.5=hcee13e7_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - commonmark=0.9.1=pyhd3eb1b0_0
  - conda=4.11.0=py38h06a4308_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=3.4.7=py38hd23ed53_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datrie=0.8.2=py38h27cfd23_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.18.1=py38h06a4308_3
  - dpath=2.0.6=py38h578d9bd_2
  - dropbox=11.34.0=pyhd8ed1ab_0
  - expat=2.2.10=he6710b0_2
  - filechunkio=1.8=py_2
  - filelock=3.9.0=py38h06a4308_0
  - flit-core=3.9.0=py38h06a4308_0
  - frozenlist=1.3.1=py38h0a891b7_1
  - ftputil=5.0.4=pyhd8ed1ab_0
  - future=0.18.2=py38_1
  - git=2.23.0=pl526hacde149_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.37=py38h06a4308_0
  - google-api-core=2.10.0=pyhd8ed1ab_0
  - google-api-python-client=2.64.0=pyhd8ed1ab_0
  - google-auth=2.12.0=pyh1a96a4e_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=py38h06a4308_0
  - google-cloud-storage=2.5.0=pyh6c4a22f_0
  - google-crc32c=1.1.2=py38h27cfd23_0
  - google-resumable-media=2.4.0=py38h06a4308_0
  - googleapis-common-protos=1.56.4=py38h06a4308_0
  - grpcio=1.42.0=py38hce63b2e_0
  - httplib2=0.20.4=pyhd8ed1ab_0
  - icu=68.1=h2531618_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - jinja2=3.1.2=py38h06a4308_0
  - jmespath=1.0.1=py38h06a4308_0
  - jsonschema=4.19.2=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter_core=4.11.1=py38h06a4308_0
  - krb5=1.19.2=hcc1bbae_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libarchive=3.5.1=hccf745f_2
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.1=he6710b0_2
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_17
  - libgfortran-ng=12.1.0=h69a702a_17
  - libgfortran5=12.1.0=hdcd56e2_17
  - libgomp=12.1.0=h8d9b700_17
  - libiconv=1.16=h7f8727e_2
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libprotobuf=3.19.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.19=h780b84a_5
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libxml2=2.9.12=h72842e0_0
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - mamba=0.15.2=py38h2aa5da1_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - multidict=6.0.2=py38h5eee18b_0
  - nbformat=5.9.2=py38h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - numexpr=2.8.1=py38hecfb737_0
  - numpy=1.22.3=py38h7a5d4dd_0
  - numpy-base=1.22.3=py38hb8be1f0_0
  - oauth2client=4.1.3=py_0
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py38h295c915_0
  - paramiko=2.11.0=pyhd8ed1ab_0
  - pcre=8.44=he6710b0_0
  - peppy=0.35.2=pyhd8ed1ab_0
  - perl=5.26.2=h14c3975_0
  - pip=23.3=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_0
  - plac=1.3.5=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h06a4308_1
  - ply=3.11=py38_0
  - prettytable=3.4.1=pyhd8ed1ab_0
  - protobuf=3.19.1=py38h295c915_0
  - psutil=5.9.0=py38h5eee18b_0
  - pulp=2.6.0=py38h578d9bd_2
  - py=1.11.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py38h5eee18b_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.9=py38h06a4308_0
  - pysftp=0.2.9=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=7.1.3=py38h578d9bd_0
  - python=3.8.10=h12debd9_8
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-irodsclient=1.1.5=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2023.3.post1=py38h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38h5eee18b_0
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - readline=8.1.2=h7f8727e_1
  - referencing=0.30.2=py38h06a4308_0
  - reproc=14.2.1=h36c2ea0_0
  - reproc-cpp=14.2.1=h58526e2_0
  - requests=2.27.1=pyhd3eb1b0_0
  - reretry=0.11.1=pyhd8ed1ab_0
  - rich=12.6.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py38h27cfd23_0
  - s3transfer=0.6.0=py38h06a4308_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - slacker=0.14.0=py_0
  - smart_open=6.2.0=pyha770c72_0
  - smmap=3.0.5=pyhd3eb1b0_0
  - snakemake-minimal=7.15.2=pyhdfd78af_0
  - sqlite=3.37.0=hc218d9a_0
  - stone=3.3.1=py38h06a4308_0
  - stopit=1.1.2=py_0
  - tabulate=0.8.10=py38h06a4308_0
  - tk=8.6.11=h1ccaba5_0
  - tomli=2.0.1=py38h06a4308_0
  - toposort=1.7=pyhd8ed1ab_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.7.1=py38h06a4308_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py38h5eee18b_0
  - yte=1.5.1=pyha770c72_2
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.5.0=ha4553b6_1

**Comment by lkhilton** [comment]
This sounds like a problem with how your PATH environment variable is set. If you 'echo $PATH' with the conda environment activated, the path to the opv12 conda environment should be at the beginning of your path. If it's not, take a look at how you've modified your PATH in your .bashrc file.

**Comment by focusonskills** [comment]
`echo $PATH` returns the opv12 enviroment at the beginning.
/home/bioinf/miniconda3/envs/opv12/bin:

`snakemake --version` returns 7.15.2 which now match with the enviroment.

However running `nice snakemake --dry-run --use-conda all -s capture_Snakefile.smk` still gives error below.

> Building DAG of jobs...
> Executing subworkflow reference_files.
> Creating specified working directory /mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/demo/reference.
> Building DAG of jobs...
> InputFunctionExceptionin line 583 of /mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk:
> Error:
>   AssertionError: The `download_oncodrive_hg19_regions` download rule doesn't have a `provider` param.
> Wildcards:
>   genome_build=grch37
>   suffix=gnomad/af-only-gnomad.grch37.vcf
> Traceback:
>   File "/mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk", line 453, in hardlink_same_provider
>   File "/mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk", line 423, in get_matching_download_rules

**Comment by lkhilton** [comment]
Thanks for your patience @focusonskills. This was a known problem addressed in #310 and should be fixed if you pull from master again.

**Comment by focusonskills** [comment]
@lkhilton 
I've updated `workflows/reference_files/2.4/reference_files.smk` with the following.
```
rule download_oncodrive_refs:
    output:
        refs = "downloads/oncodrive/datasets/genomereference/{oncodrive_build}.master",
        stops = "downloads/oncodrive/datasets/genestops/{oncodrive_build}.master"
    params:
        outdir = "downloads/oncodrive/{version}/",
        provider = lambda w: config["genome_builds"][w.version]["provider"]
```
I've also checked that `modules/oncodriveclustl/1.0/oncodriveclustl.smk` match with the suggested correction below.
```
rule _oncodriveclustl_run:
    input:
        maf = str(rules._oncodriveclustl_format_input.output.maf),
        reference = lambda w: reference_files("downloads/oncodrive/{genome_build}/datasets/genomereference/" + ONCODRIVE_BUILD_DICT[w.genome_build] + ".master"),
        region = _get_region
    output:
        txt = CFG["dirs"]["oncodriveclustl"] + "{genome_build}/{sample_set}--{launch_date}/{md5sum}/{region}/elements_results.txt",
        tsv = CFG["dirs"]["oncodriveclustl"] + "{genome_build}/{sample_set}--{launch_date}/{md5sum}/{region}/clusters_results.tsv",
        png = CFG["dirs"]["oncodriveclustl"] + "{genome_build}/{sample_set}--{launch_date}/{md5sum}/{region}/quantile_quantile_plot.png"
    log:
        stdout = CFG["logs"]["oncodriveclustl"] + "{genome_build}/{sample_set}--{launch_date}/{md5sum}/{region}/oncodriveclustl.stdout.log",
        stderr = CFG["logs"]["oncodriveclustl"] + "{genome_build}/{sample_set}--{launch_date}/{md5sum}/{region}/oncodriveclustl.stderr.log"
    params:
        local_path = CFG["reference_files_directory"] + "{genome_build}/",
        build = lambda w: (w.genome_build).replace("grch37","hg19").replace("grch38","hg38"),
        command_line_options = CFG["options"]["clustl_options"] if CFG["options"]["clustl_options"] is not None else ""
```
However `nice snakemake --dry-run --use-conda all -s capture_Snakefile.smk` still returns AssertionError below.

> Building DAG of jobs...
> Executing subworkflow reference_files.
> Creating specified working directory /mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/demo/reference.
> Building DAG of jobs...
> InputFunctionExceptionin line 583 of /mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk:
> Error:
>   AssertionError: The `download_oncodrive_hg19_regions` download rule doesn't have a `provider` param.
> Wildcards:
>   genome_build=grch37
>   suffix=main_chromosomes/main_chromosomes.grch37.txt
> Traceback:
>   File "/mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk", line 453, in hardlink_same_provider
>   File "/mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/workflows/reference_files/2.4/reference_files_header.smk", line 423, in get_matching_download_rules

**Comment by lkhilton** [comment]
Could you please pull from master one more time? The commit I made to fix the assertion error was overwritten in another branch. You should see [these changes](https://github.com/LCR-BCCRC/lcr-modules/pull/315/files) after pulling the latest changes.

**Comment by focusonskills** [comment]
Thank you!
The reference files have been successfully generated with the update and there are no more assertion error.
However I'm encountering some other errors downstream with Battenberg/ASCAT installation.
Could you shed some light on the issue?

> Activating conda environment: .snakemake/conda/1ea4ad9da9e4539afd010c34139325fa_
> Downloading GitHub repo Crick-CancerGenomics/ascat@master
> Skipping 3 packages not available: GenomicRanges, IRanges, S4Vectors
> Installing 8 packages: data.table, doParallel, foreach, GenomicRanges, IRanges, RColorBrewer, S4Vectors, iterators
> Error: Failed to install 'ASCAT' from GitHub:
>   (converted from warning) packages ‘GenomicRanges’, ‘IRanges’, ‘S4Vectors’ are not available (for R version 3.6.3)
> Execution halted
> [Tue Jun  4 14:45:07 2024]
> Error in rule _install_battenberg:
>     jobid: 137
>     output: results/battenberg-1.2/00-inputs/battenberg_dependencies_installed.success
>     log: results/battenberg-1.2/logs/launched-2024-06-04-at-14-44-48/00-inputs/input.log (check log file(s) for error message)
>     conda-env: /mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-modules/demo/.snakemake/conda/a85e0be326fb70ac2ccc6d95cb4ecce5_
>     shell:
>         R -q --vanilla -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")' >> results/battenberg-1.2/logs/launched-2024-06-04-at-14-44-48/00-inputs/input.log && ##move some of this to config?
>         R -q --vanilla -e 'devtools::install_github("morinlab/battenberg")' >> results/battenberg-1.2/logs/launched-2024-06-04-at-14-44-48/00-inputs/input.log && ##move some of this to config?
>         touch results/battenberg-1.2/00-inputs/battenberg_dependencies_installed.success
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by Kdreval** [comment]
Hi @focusonskills ,
I trust this issue is related to the `devtools` run of `remotes` under the hood, which recently changed how it finds non-CRAN packages. It basically now refuses to install anything from BioConductor complaining that the package was not found. I think adding the argument `repos = BiocManager::repositories()` to the devtools call should fix the problem, so the line `R -q --vanilla -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")' ` should become `R -q --vanilla -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT", repos = BiocManager::repositories())' ` . Can you please see if this fixes the error?

Thank you!

**Comment by focusonskills** [comment]
@Kdreval 
It is able to locate the packages now but it still failed to install some of the packages. 

> * installing *source* package ‘data.table’ ...
> ** package ‘data.table’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> fread.c: In function 'freadMain':
> fread.c:1301:7: warning: ignoring return value of 'strtod', declared with attribute warn_unused_result [-Wunused-result]
>        (void)strtod(ch, &end);  // careful not to let "" get to here as strtod considers "" numeric
>        ^~~~~~~~~~~~~~~~~~~~~~
> /mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-pipeline/lcr-modules/demo/.snakemake/conda/2239fcac3430199448647436028de9d0_/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgomp
> collect2: error: ld returned 1 exit status
> make: *** [/mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-pipeline/lcr-modules/demo/.snakemake/conda/2239fcac3430199448647436028de9d0_/lib/R/share/make/shlib.mk:6: data.table.so] Error 1
> ERROR: compilation failed for package ‘data.table’
> * removing ‘/mnt/raid/Analysis/Ongoing/Haloplex/OldPipeline/lcr-pipeline/lcr-modules/demo/.snakemake/conda/2239fcac3430199448647436028de9d0_/lib/R/library/data.table’
> Error: Failed to install 'ASCAT' from GitHub:
>   (converted from warning) installation of package ‘data.table’ had non-zero exit status
> Execution halted

**Comment by lkhilton** [comment]
As of #327 we've updated the PyPi repository for Oncopipe and modified the `demo/env.yaml` file. You should now be able to install the correct version of Snakemake and all dependencies (including Oncopipe) with the command outlined in the README. 

There is also a pending PR #326 that includes updates to the battenberg conda environment that should resolve the battenberg installation issues. 

This should resolve these issues, please let us know if there are any further stumbling blocks.
