### ISSUE TITLE
fishHook - add gene list

### ISSUE THREAD

**Issue by gillissierra** [LCR-BCCRC/lcr-modules#305]
- Add the GRCh37 gene list that is provided by the developers. http://mskilab.com/fishHook/hg19/gencode.v19.genes.gtf'))
- Change the yaml to have a TRUE/FALSE for whether to use the gene list in the model. Note in the yaml that it is mutually exclusive with finding significant regions using tiles, which will remain the default.

Related is the lcr-scripts [Issue 60](https://github.com/LCR-BCCRC/lcr-scripts/issues/60), which will ensure the input to the fishHook script is for GRCh37

**Comment by Kdreval** [comment]
This can be closed now, right?

**Comment by gillissierra** [comment]
Not yet, I haven't implemented this

**Comment by gillissierra** [comment]
To keep this flexible with the use of either tiles or gene lists, the module can stay as is. Users following the fishHook developer's tutorial will be able to easily find the gene list .gtf they used.
