### ISSUE TITLE
Control-FREEC

### ISSUE THREAD

**Issue by BrunoGrandePhD** [LCR-BCCRC/lcr-modules#31]
https://github.com/BoevaLab/FREEC

**Comment by rdmorin** [comment]
Does @lkhilton or anyone else have a working Snakefile that could be used as a starting point?

**Comment by rdmorin** [comment]
Does anyone have a working Snakefile that could be used as the basis for this?

**Comment by Jwong684** [comment]
I have a snakemake with controlFREEC and ichorCNA for the lowpassWGS data:

/projects/dscott_prj/CCSRI_1500/lowpassWGS/snakefile

**Comment by rdmorin** [comment]
Can you open up permissions on that file?

**Comment by Jwong684** [comment]
Okay it should be readable for everyone (chmod 774)

**Comment by rdmorin** [comment]
Thanks. Did you change any parameters for low-pass WGS or is this the same settings used for deep/normal WGS?

**Comment by Jwong684** [comment]
The only parameter I changed is the predicted ploidy to (2,3) to match the default in ichorCNA. 

The default:
/projects/dscott_prj/CCSRI_1500/lowpassWGS/config/freec/config_WGS_ploidy2to8.txt

The one I used to compare to ichorCNA:
/projects/dscott_prj/CCSRI_1500/lowpassWGS/config/freec/config_WGS.txt

**Comment by rdmorin** [comment]
Are you sure you didn't also increase the window size from 50kb to 1 Mb?

**Comment by rdmorin** [comment]
There are some other differences here too:
```
diff config/freec/config_WGS_50kb_window.txt config/freec/config_WGS.txt
6a7
> SambambaThreads = 2
12c13,14
< breakPointThreshold = .8
---
> # breakpointTheshold changed to 0.6 from 0.8 for windowSize 1Mb (before there would be an error with stdou)
> breakPointThreshold = .6
15c17,19
< window = 50000
---
> window = 1000000
> # also need to set a step parameter (otherwise error (wrong vector boundaries))
> step = 100000

**Comment by Jwong684** [comment]
Oh shoot! Yes. The 1Mb change was also to match ichorCNA. Control-FREEC uses 50kb windows. And also the breakpointThreshold (good thing I commented my changes).

**Comment by Jwong684** [comment]
For reference:

This is the config_WGS.txt they used:

WGS:
https://github.com/BoevaLab/FREEC/blob/master/data/config_WGS.txt

Exome:
https://github.com/BoevaLab/FREEC/blob/master/data/config_exome.txt

**Comment by rdmorin** [comment]
Yes, also, when in doubt, diff is helpful for finding such things. Thanks for the reference configs.

**Comment by rdmorin** [comment]
Too bad they want each chromosome in it's own fasta file (WHY???). 
Did @lkhilton download these files from somewhere? 
/projects/rmorin/projects/DLBCL_DHITsig_genomes/reference/FREEC/hg19

**Comment by lkhilton** [comment]
I would have obtained most of them from here: 
http://boevalab.inf.ethz.ch/FREEC/tutorial.html#install

**Comment by rdmorin** [comment]
No hg38? Argh

**Comment by rdmorin** [comment]
Wait, they have a single file for hg38 but most of them are only for the older builds. What a tease!
```
up to 2 mismatches, hg38, read length 100bp

**Comment by rdmorin** [comment]
Version 1.1 has been merged.
