### ISSUE TITLE
Add function for automatically increasing `mem_mb` on retries

### ISSUE THREAD

**Issue by BrunoGrandePhD** [LCR-BCCRC/lcr-modules#33]
Snakemake allows resources like `mem_mb` to be functions with an `attempt` parameter. This makes it easy to wrap any value to be automatically increase (_e.g._ by 50%) on failed attempts, assuming memory was the issue. 

https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources

**Comment by Kdreval** [comment]
This has been inplemented through a current practice of specifying mem_mb through params. Here is an example:
https://github.com/LCR-BCCRC/lcr-modules/blob/79fd7f4e6a9916a94af3c668b0905249e6969d98/modules/sage/1.1/sage.smk#L162
