### ISSUE TITLE
Develop testing suite for oncopipe package

### ISSUE THREAD

**Issue by BrunoGrandePhD** [LCR-BCCRC/lcr-modules#34]
Before refactoring the `oncopipe` package (see #27), it would be really useful to create a suite of tests to ensure no regressions occurs.

**Comment by BrunoGrandePhD** [comment]
Good resource to set up testing: https://realpython.com/python-testing/

It seems that PyTest might be the simplest to set up: https://docs.pytest.org/en/latest/

This blog post also suggests pytest: http://www.rohitschauhan.com/index.php/2018/07/05/python-relative-benefits-of-pytest-unittest-nose-and-doctest/

We can just start with a single Python script (_e.g._ `test_oncopipe.py`). I can organize the tests later once I reorganize `oncopipe`.

**Comment by whelena** [comment]
I'm wondering how to run tests on functions without a return value. I did some research and come across the python `Mock` package. I haven't gone too in depth into its documentation but  from what I understand it would let me assert if a function is called and if the arguments fed into the functions are accurate using something like:
Do you have any inputs or suggestions for a different approach?

**Comment by BrunoGrandePhD** [comment]
I think it depends on the function. Some functions could probably be further modularized into smaller functions that do have return values. Since I'll be refactoring `oncopipe`, I don't want to spend too much time creating custom tests to account for the current structure.

**Comment by whelena** [comment]
Okay, so far I only managed to test the simplest functions and I'm not really sure what's the best way to test out functions that require snakemake config files or wildcards.

**Comment by BrunoGrandePhD** [comment]
Just a heads-up, I sometimes use the `inspect` package to pull variables from the parent scope/frame. Here's [an example] of me doing this in `setup_module()`. Since you can't pass `config` as an argument, you'll just need to define `config` in the test function before calling `setup_module()`.

**Comment by BrunoGrandePhD** [comment]
> Okay, so far I only managed to test the simplest functions and I'm not really sure what's the best way to test out functions that require snakemake config files or wildcards.

Feel free to load the project and module config used in the demo Snakefile using the `yaml` package. You can use the `snakemake.utils.update_config()` function to follow the same approach as Snakemake when it comes to overwriting the config with newer config files.

**Comment by whelena** [comment]
hmm okay, I will try that. Thank you!

**Comment by whelena** [comment]
> Just a heads-up, I sometimes use the `inspect` package to pull variables from the parent scope/frame. Here's [an example] of me doing this in `setup_module()`. Since you can't pass `config` as an argument, you'll just need to define `config` in the test function before calling `setup_module()`.

I'll read up on that package too then
