### ISSUE TITLE
Implement support for sample-based modules for `op.switch_on_column()`

### ISSUE THREAD

**Issue by BrunoGrandePhD** [LCR-BCCRC/lcr-modules#35]

**Comment by BrunoGrandePhD** [comment]
I could replace the `match_on` argument with a more general `wildcard_name` argument, which would allow the user to specify `"sample_id"`, `"tumour_id"`, or `"normal_id"`.

**Comment by whelena** [comment]
@BrunoGrandePhD I implemented it into some of my modules and pushed the edit to master. Would the new edits be installed using `pip install oncopipe` or do users have to use `pip install -e lcr-modules/oncopipe`?

**Comment by BrunoGrandePhD** [comment]
I created a new release on GitHub (v1.0.7), which automatically deploys to PyPI. 

https://github.com/LCR-BCCRC/lcr-modules/releases
https://pypi.org/project/oncopipe/
