### ISSUE TITLE
Directing Manta to look at STAR bams

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#39]
I've pulled the latest master (00d1cca) and installed oncopipe. When I try to launch the demo Snakefile I get this error message: 

```
MissingInputException in line 41 of /projects/rmorin/software/lcr-modules/modules/manta/2.0/manta.smk:
Missing input files for rule _manta_input_bam:
data/TCRBOA7-T-RNA.bam.bai
data/TCRBOA7-T-RNA.bam
```

I guess since the manta module is set to look for bam files in the data directory, it expects to find an RNAseq bam file there. However we really want it to look at the bam in `data` for capture, and at the bam output by STAR for RNAseq. How can a user set up their config to use a different input directory for manta depending on whether the input is RNAseq or other?

**Comment by BrunoGrandePhD** [comment]
For some reason, the placeholder files for the RNA-seq BAM file were missing. I added these in 30e24a5c2afc98ed9913a6849f03d3f6d1e444a0. 

I added some notes for GSC users so they can benefit from the local files that already exist. This one:

> You can set the reference_files working directory (workdir) to the following file path in order to benefit from pregenerated reference files:
> ```
> /projects/bgrande/reference_files
> ```

And this one:

> You can symlink local copies of the test data using the following command:
> ```
> ln -sf /projects/bgrande/lcr-modules/test_data/*.{bam,bai,fastq.gz} ./demo/data/
> ```

So, make sure you replace the empty placeholder files with symlinks using the above command to avoid downloading files that you already have access to. 

And to address your question about conditionally using BAM files based on the `seq_type`, I updated the example for the Conditional Module Behaviour section to perform exactly this task. I show multiple iterations of the same basic approach to show how to use various features to simplify the code. 

https://lcr-modules.readthedocs.io/en/latest/for_users.html#conditional-module-behaviour
