### ISSUE TITLE
oncopipe installation from pip appears to be broken

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#40]
I get the following error when I attempt to build the reference directory after installing oncopipe from pip (`pip install oncopipe`):

AttributeError in line 125 of /home/rmorin/lcr-modules/workflows/reference_files/1.0/reference_files.smk:
module 'oncopipe' has no attribute 'as_one_line'
  File "/home/rmorin/lcr-modules/workflows/reference_files/1.0/prepare_reference_files.smk", line 28, in <module>
  File "/home/rmorin/lcr-modules/workflows/reference_files/1.0/reference_files.smk", line 125, in <module>

**Workaround:**
Running the installation from the oncopipe version in the repo fixes this issue. 

`pip install -e lcr-modules/oncopipe`

Installing collected packages: oncopipe
  Attempting uninstall: oncopipe
    Found existing installation: oncopipe 1.0.0
    Uninstalling oncopipe-1.0.0:
      Successfully uninstalled oncopipe-1.0.0
  Running setup.py develop for oncopipe
Successfully installed oncopipe

`/workflows/reference_files/1.0/prepare_reference_files.sh /projects/rmorin/TEMP/lcr-modules-reference/
Building DAG of jobs...`

**Comment by BrunoGrandePhD** [comment]
Thanks for picking up on this! I had misconfigured the `setup.py` script. The PyPI version is working now. 
```bash
pip install oncopipe==1.0.2
```

**Comment by rdmorin** [comment]
Thanks. I confirm this is resolved. The ==1.0.2 also looks to be unnecessary as it defaults to the latest version.
