### ISSUE TITLE
ChildIOException

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#43]
After my last successful run of my sequenza pipeline I deleted an intermediate file and tried re-running it. Interestingly, this error is not from the same sample as the file I deleted so I don't know what caused this. Any idea what this might relate to? 

Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
('/home/rmorin/lcr-modules/demo/results/sequenza-1.0/03-plots/capture--grch37/TCRBOA7-T-WEX--TCRBOA7-N-WEX--matched/TCRBOA7-T-WEX_filtered_segments.igv.seg', _sequenza_filtered_igv_segments)
('/home/rmorin/lcr-modules/demo/results/sequenza-1.0/03-plots/capture--grch37/TCRBOA7-T-WEX--TCRBOA7-N-WEX--matched/TCRBOA7-T-WEX_filtered_segments.igv.seg', _sequenza_output_seg)

**Comment by BrunoGrandePhD** [comment]
Can you confirm that all of your local changes are pushed to GitHub under the `module/sequenza/1.0` branch? This way, I can debug when reviewing your PR, #41.

**Comment by rdmorin** [comment]
Turns out I had made a few changes that I hadn't pushed. I'm going to look at this for a few more minutes and see if I can find the problem. If not, I'll commit and push and let you know

**Comment by BrunoGrandePhD** [comment]
My guess is that the `_sequenza_output_seg`is using the `CFG["dirs"]["plots"]` instead of `CFG["dirs"]["outputs"]`. As a result, both rules produce the same output file.

**Comment by rdmorin** [comment]
```rule _sequenza_output_seg:
    input:
        seg = rules._sequenza_filtered_igv_segments.output.igv
    output:
        seg = CFG["dirs"]["outputs"] + "seg/{seq_type}--{genome_build}/{tumour_id}--{normal_id}--{pair_status}.output.filt.seg"
    run:
        op.relative_symlink(input.seg, output.seg)
```

**Comment by BrunoGrandePhD** [comment]
You can use triple backticks just like in Slack. I updated your comment.

**Comment by BrunoGrandePhD** [comment]
I'm confused then why the error messages says that 
```
results/sequenza-1.0/03-plots/capture--grch37/TCRBOA7-T-WEX--TCRBOA7-N-WEX--matched/TCRBOA7-T-WEX_filtered_segments.igv.seg
```
is an output of `_sequenza_output_seg`.

**Comment by rdmorin** [comment]
I am also baffled by it. @lkhilton and I are discussing in Slack currently.
