### ISSUE TITLE
MiXCR

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#44]
https://mixcr.readthedocs.io/en/master/

**Comment by rdmorin** [comment]
I was going to assign this to Anita dos Santos but I don't see her. Can we add her to the contributors?

**Comment by BrunoGrandePhD** [comment]
What's her GitHub username?

**Comment by rdmorin** [comment]
adossantos1

**Comment by BrunoGrandePhD** [comment]
Invite sent!

**Comment by rdmorin** [comment]
Module from @adossantos1 merged to master
