### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by BrunoGrandePhD** [LCR-BCCRC/lcr-modules#5]
I've put together the following list of feature requests to keep in mind when designing the pipelines based on a discussion with the CLC bioinformaticians. I've also listed some pros and cons to consider for each feature. 

### Terminology

Before going over the features, I wanted to bring up the issue of terminology. During the meeting, we agreed to refer to the modular units as modules (what I've referred to as pipelines so far), and reserve the term pipeline for an arrangement of modules. For example, Strelka variant calling would be encapsulated into a module whereas genome analysis would be a pipeline consisting of multiple modules (probably one for read alignment and one for each mutation type). The steps within each module are referred to as rules to adopt the Snakemake term. 

## Flexible Modules

The motivation for these modules is to standardize commonly performed analyses. Hence, they are expected to be run without modification in most cases. In practice though, tweaks are often required in the research setting. For this reason, these modules should remain flexible and easily allow for modifications. This primarily hinges on **readability** and **accessibility** of the Snakefiles. As long as users can understand them (assuming some Snakemake knowledge), they should be able to add, remove or edit rules. 

**Pros**
- Modules are more useful for a larger number of people if they can be easily tweaked. 
- By having the modules more readable, they will be easier to maintain in the long run. 

**Cons**
- Prioritizing readability might preclude more advanced features that require more complicated code in the Snakefiles. 

## Granular Rules

Some have experienced modules where many tasks are being done in one rule. In turn, this obfuscates the module—making it harder to understand—and complicates the addition or removal of individual tasks (_e.g._ between two tasks captured in one rule). To avoid this issue, I propose we follow the Unix philosophy and limit each rule to a small task. 

**Pros**
- Modules will be easier to understand. 
- Rules can more readily be shared between modules if we pursue the route of [Snakemake wrappers](https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#wrappers). 

**Cons**
- Obviously, this will make modules longer to develop. 

## Modular Design

Ideally, the various modules should be modular and easily feed into one another. For example, a read alignment module should be readily "connectable" with a variant detection module. The modules should expose an easy way of defining the input files. Practically speaking, this means that we should ensure that the inputs and outputs between various pipelines should match up as much as possible. In other words, in a pipeline where the modules are the edges and the nodes are the intermediate file types, we want to minimize the different types of nodes. 

For example, a Salmon RNA-seq module would be nicely complemented by a STAR/featureCount RNA-seq module. Both modules should take paired FASTQ files as input and output expression matrices using the same format (ideally). Here, while STAR/featureCount will produce gene-level counts, Salmon will produce gene-level and transcript-level counts. It's okay if one module generates additional files. 

**Pros**
- Running similar pipelines and comparing their results will be easy. 
- Less "glue" will be needed if the number of different intermediate files is kept to a minimum. 
- A modular design will make it easy to assemble meta-modules (or pipelines) that incorporate related modules (_e.g._ an exome analysis pipeline). 

**Cons**
- Trying to stick with the fewest number of different intermediate files might reduce the flexibility of the modules we can create (if we are too restrictive). 

## User-configurable Cluster Parameters

Given that resource requirements can vary wildly—even for the same rule—based on the input data, it is important to that the number of CPUs and memory can be configured by the user. This way, if an exome is being run through a module typically run on genomes, it will be easy to reduce the resource requirements, which in turn will reduce the job wait time in the cluster queue. 

**Pros**
- This will make modules more portable to different compute environments. 
- By being able to refine the resource requirements for each module, jobs will run sooner on the cluster. 
- By storing resource requirements for different types of module inputs, that knowledge can be shared among the module users (_e.g._ FF genomes need 8 GB in this rule, but FFPE genomes need double that). 

**Cons**
- If we add configurable cluster parameters for each rule, this will add significant bulk to the configuration required for each module. 

## Software Versioning

These modules should ideally ensure that the versions of software tools being used are tracked. This can naturally be done using conda environments. However, given our past experience with packages suddenly disappearing online and environments being unable to be instantiated just three weeks after they were originally created, I propose we adopt a mixed strategy: (1) we store the complete environment YAML file (with or without build IDs); (2) we also store the environment specification for just the packages that we requested at the command line (_i.e._ using the `--from-history` conda option); and (3) after instantiating a read-only local copy on the GSC file system, we store the path to this conda environment for local use. 

**Pros**
- This will tremendously help with ensuring the reproducibility of our analyses over time. 

**Cons**
- As I mentioned, conda can be flaky, so we must take precautions here to avoid getting bitten. 
- This involves extra work for each module because three environments will need to be specified. 

## Automatic Logging

The automatic logging of commands, stdout, and stderr would make these modules even more useful and reproducible. Apparently, the level of logging is slightly different between running jobs locally vs. on the cluster. This discrepancy should be eliminated. I'm aware that a lot of stored in the `.snakemake` directory, but I don't think those logs are very discoverable. 

**Pros**
- These logs can help answer questions if they come up down the line. 

**Cons**
- This feature might add a lot of overhead to each rule depending on how it's implemented. 

## File Permissions

These modules should come with guidelines on how to ensure proper file permissions. In particular, it would be great if the owning group of the output files as well as the group permissions (read and write) were automatically enabled for all output files as well as the hidden `.snakemake` files. 

**Pros**
- More than one person could easily work on a project if this was implemented. 

**Cons**
- This feature might add a lot of overhead to each rule depending on how it's implemented.

**Comment by rdmorin** [comment]
I would also like us to pay attention to file permissions such that more than one user in the same group can run snakemake in the same project folder. i.e. setting group-write permissions for all output files and hidden files/folders created by snakemake. I'll let you decide whether or not this counts as a feature request. It may make more sense to deploy this "feature" at the level of the main Snakefile or (as you suggested previously) the master environment in the project folder. Nonetheless, I think we should roll it into this software such that users can easily adopt an environment that automatically handles file permissions.

**Comment by BrunoGrandePhD** [comment]
Comments

**Comment by rdmorin** [comment]
We are going to have to make all pipelines portable enough to allow them to run in Amazon EC2, pulling input files from remote URLs and S3 buckets as needed.

**Comment by rdmorin** [comment]
Automatic/elegant handling of cram when the bam has been compressed

**Comment by BrunoGrandePhD** [comment]
With the initial release of `lcr-modules`, I'm closing this issue. We will be tracking feature requests in individual tickets.
