### ISSUE TITLE
cookiecutter always adds unmatched normal to default config

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#50]
Could the cookiecutter be modified to ask whether the user wants to analyze unpaired tumours with with unmatched normal? I don't think this is asked (or at least not in a way that is intuitive) so I keep ending up with this config. 

```pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False```

**Comment by BrunoGrandePhD** [comment]
That can definitely be done. In fact, with the new `generate_pairs()` function, I think the same options should be available for the cookiecutter template, namely `matched_only`, `allow_unmatched`, and `no_normal` (in addition to `omit`). I can tackle this on the weekend.
