### ISSUE TITLE
sambamba error

### ISSUE THREAD

**Issue by Kdreval** [LCR-BCCRC/lcr-modules#58]
I was testing the lcr-modules using a demo snakefile and demo samples. The workflow failed during running the sambamba markdup step. I looked on the log and found that this step failed because it was not able to open the new file: 
`sambamba-markdup: Cannot open file "/tmp/sambamba-pid2186658-markdup-lhow/PairedEndsInfoqbqa9" in mode "w+" (Too many open files)`
For solution, I found that this is a common error and here https://github.com/biod/sambamba/issues/177 it was suggested to increase the number of temporary files by specifying the flag --overflow-list-size 600000 . I tried this and it helped to execute the workflow. I do not think that these many temporary files were needed, but this flag helped to proceed with workflow.
However, to add the flag, I went to the snakefile `utils.smk` in utils module.

**Comment by BrunoGrandePhD** [comment]
Can you try increasing your ulimit? Specifically, `ulimit -n` should ideally be a higher number. 

https://lcr-modules.readthedocs.io/en/latest/for_users.html#gsc-ulimit-setup

**Comment by Kdreval** [comment]
Sure! I'll try it today and will update here on how it worked out.
I was testing it by running on Thanos. The current `ulimit -n `says 1024. I will do` ulimit -n 100000`

**Comment by rdmorin** [comment]
@BrunoGrandePhD don't you find it concerning that it needs more than 1000 files open at once? My inclination is this points towards it not using memory optimally here and spawns more tempfiles than it theoretically needs but perhaps theres some other reason?

**Comment by BrunoGrandePhD** [comment]
You have to test different ulimits until it works. Sometimes, the admin has set a hard limit that users can go above. For example, I found out that 50000 is the limit on n104 (numbers cluster head node):
```
# This works
$ ulimit -n 50000

# This doesn't work
$ ulimit -n 50001
-bash: ulimit: open files: cannot modify limit: Operation not permitted
```

**Comment by BrunoGrandePhD** [comment]
Snakemake spawns many files on its own. It's not clear here whether most files are spawned by Snakemake or Sambamba. Nevertheless, I've asked @whelena to add `--overflow-list-size 600000` as a default option for sambamba in the upcoming update to the `utils` module. See #57.

**Comment by rdmorin** [comment]
Sounds good. Thanks
