### ISSUE TITLE
BEDPE files from Manta have a massive header

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#59]
It looks like the vcf to bedpe conversion is leaving the VCF header or adding a new (similar) header to the bedpe files. The header looks to be 236 lines with the last line referring to the columns and the rest somewhat extraneous. Is the inclusion of this on purpose? If so, do we really want this?

```
##fileformat=BEDPE
##fileDate=20200630
##source=GenerateSVCandidates 1.6.0
##reference=file:///projects/rmorin/projects/gambl-repos/gambl-rmorin/ref/lcr-modules-references/genomes/hg38/genome_fasta/genome.fa
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>

**Comment by lkhilton** [comment]
I'm sure we don't _need_ the whole thing, but it contains useful info about the INFO field that's carried over from the VCF. If you're importing into R you can use the `comment.char = "##"` option in `read.delim` or `comment = "##"` in `read_tsv` to skip the headers.

**Comment by BrunoGrandePhD** [comment]
The svtools vcftobedpe utility stores the VCF header in the output BEDPE. I'm guessing this is because the BEDPE file contains the INFO and FORMAT VCF fields, and these header lines provide context. I erred on the side of inclusion since they can easily be removed with `grep -v '^##' ...`. If this header poses a more serious problem, we can consider removing it.

**Comment by BrunoGrandePhD** [comment]
@lkhilton: Good tips for handling these in R!

**Comment by rdmorin** [comment]
If they're redundant with the VCF I just wonder why we would want to keep them in the BED.

**Comment by BrunoGrandePhD** [comment]
I suspect the BEDPE files will be used down the line without the VCF files. Since the headers don't do any harm, I'm going to leave this as is, but if someone else raises this as a concern, we can look into getting rid of the headers.
