### ISSUE TITLE
SigProfiler/SignatureAnalyzer (mutational signature analysis)

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#6]
We should try to adapt the wrapper code Luka and Eric Zhao provided into a portable pipeline. I'm sure Luka would appreciate having his code made more portable. Perhaps he even wants to be involved in the process.

**Comment by rdmorin** [comment]
We should test out the methods from PCAWG. It's not worth implementing a module for the older method as long as the more sophisticated ones work in our hands.

**Comment by Kdreval** [comment]
This has been resolved by Prasath's Sigprofiler module in PR https://github.com/LCR-BCCRC/lcr-modules/pull/189
