### ISSUE TITLE
Manta 99-outputs contains only "dispatched" files

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#66]
The current (v 2.2) Manta workflow does not symlink any of the actual results from Manta to 99-outputs. Shouldn't at least the bed files be symlinked there or am I misunderstanding the purpose of this directory? 

```
ls results/icgc_dart/manta-2.2/99-outputs/dispatched/genome--hg38/
SP116652--SP116651--matched.dispatched  SP59270--SP59269--matched.dispatched  SP59284--SP59282--matched.dispatched  SP59332--SP59330--matched.dispatched

**Comment by whelena** [comment]
Did it run into any errors while running? The bed and vcf files should be symlinked into `99-outputs/bed/` and `99-outputs/vcf/` respectively
