### ISSUE TITLE
Strelka2 doesn't work properly with Manta vcfs

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#67]
I tried running Strelka2 1.0 with an output from the latest Manta module (2.2) and it failed when trying to compress the files that were already compressed during the Manta workflow. I don't know if the compression and indexing is a more recent addition to Manta but if so, the Strelka2 module needs to be updated to fix this. If someone can confirm I'm happy to make the patch. It's currently working with this modification:

```
rule _strelka_input_vcf:
    input:
        vcf = CFG["inputs"]["candidate_small_indels"],
        tbi = CFG["inputs"]["candidate_small_indels"] + ".tbi"
    output:
        vcf = CFG["dirs"]["inputs"] + "{seq_type}--{genome_build}/vcf/{tumour_id}--{normal_id}--{pair_status}.candidateSmallIndels.vcf.gz",
        tbi = CFG["dirs"]["inputs"] + "{seq_type}--{genome_build}/vcf/{tumour_id}--{normal_id}--{pair_status}.candidateSmallIndels.vcf.gz.tbi"
    run:
        op.relative_symlink(input.vcf, output.vcf)
        op.relative_symlink(input.tbi, output.tbi)

#    params:
#        vcf = CFG["inputs"].get("candidate_small_indels_vcf") or "",
#        tbi = CFG["inputs"].get("candidate_small_indels_tbi") or ""
#    conda:
#        CFG["conda_envs"]["tabix"]
#    shell:
#        op.as_one_line("""
#        bgzip -c {input.manta_vcf} > {output.vcf}
#            &&
#        tabix {output.vcf}
#        """)

**Comment by rdmorin** [comment]
@whelena you are probably the most familiar with this

**Comment by whelena** [comment]
I can take a look, I think the last time I tested was with manta 2.1.

**Comment by whelena** [comment]
I think I know what the issue is, are you using the `candidateSmallIndels` from `99-outputs` or `02-manta`? 

I was able to run it successfully using: 
```
candidate_small_indels: "results/manta-2.2/99-outputs/vcf/{seq_type}--{genome_build}/candidateSmallIndels/{tumour_id}--{normal_id}--{pair_status}.candidateSmallIndels.vcf"
```

**Comment by rdmorin** [comment]
02-manta

Let me get this straight... is the Manta pipeline decompressing the candidateSmallIndels only for Strelka to then re-compress it before it runs?

**Comment by whelena** [comment]
yes, I didn't make any changes to manta but now that you said that maybe it would be best that manta outputs all of its vcf files in its compressed form as well

**Comment by rdmorin** [comment]
I can see why users might want them in a decompressed state for other downstream applications. Let's just leave it as is for now.
