### ISSUE TITLE
vcf2maf pipeline

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#7]
I've created one of these that uses a Docker image. It should be easily modified to make that optional and use conda instead. I haven't tried to get vcf2maf working via conda.

**Comment by rdmorin** [comment]
Has there been any progress on this one? I have some suggestions that may help. We should chat, @whelena

**Comment by whelena** [comment]
I have a working module that I have tested using vcf files from varscan. The module is based on the master branch and I am waiting for the most recent updates from Bruno before finallizing it. I will reach out to you on slack to discuss details.
