### ISSUE TITLE
Strelka does not complete failed missing vcf files

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#74]
The approach for inferring the Strelka output file names doesn't seem to allow me to rescue failed runs that have an empty output directory. I get the following error when I try to generate the outputs for one of these:

```
gzip: results/gambl/strelka-1.1/02-strelka/genome--grch37/05-20006T--05-20006N--matched/results/variants/somatic.snvs.vcf.gz: No such file or directory
[Mon Aug 10 14:37:49 2020]
Error in rule _strelka_decompress_vcf:
    jobid: 1
    output: results/gambl/strelka-1.1/03-filtered/genome--grch37/05-20006T--05-20006N--matched/somatic.snvs.vcf
    shell:
        gzip -dc results/gambl/strelka-1.1/02-strelka/genome--grch37/05-20006T--05-20006N--matched/results/variants/somatic.snvs.vcf.gz > results/gambl/strelka-1.1/03-filtered/genome--grch37/05-20006T--05-20006N--matched/somatic.snvs.vcf
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

Is there a way around this or will this module have to be updated to handle this situation more elegantly?

**Comment by rdmorin** [comment]
FYI @whelena and @BrunoGrandePhD I'm going to attempt a fix for this that separates paired and unpaired analyses a bit more. The problem really comes down to the pipeline not knowing what files should be in that directory due to the variable naming of output files in the two modes.

**Comment by rdmorin** [comment]
@lkhilton did you mention some time ago that you had thought of a fix for this?

**Comment by Kdreval** [comment]
Assuming this was fixed as there are no issues reported with strelka outputs and it was run on all of gambl
