### ISSUE TITLE
Implement testing process for demo project

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#82]
After a module is added to the demo the entire pipeline should be run on the test data automatically and
1) ensure error-free completion
2) expected outputs are generated
3) DAG is output showing all the steps for the entire workflow on the demo data

**Comment by ckrushton** [comment]
I would like to plug Travis-CI for this exact purpose

**Comment by rdmorin** [comment]
:100:

**Comment by Kdreval** [comment]
Closing this as duplicate with #288
