### ISSUE TITLE
Add bam and disk_mb resources to all rules in every workflow to allow user-specified throttling

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#92]
Any workflows with very large on-disk footprints may also need to be configured with grouped rules to ensure consecutive running of subsequent jobs rather than additional jobs being launched before the latter steps complete.

**Comment by lkhilton** [comment]
I've been telling everyone to use resource unpacking and specify default resource values in the config. I think this has mostly been addressed but I think we should add it as a requirement in new and updated modules, what do you think?

**Comment by rdmorin** [comment]
Fully onboard with default resource values but I admit I don't yet understand the benefits of it or the drawbacks of not having resource packing consistently used.

**Comment by rdmorin** [comment]
Is resource unpacking documented somewhere?

**Comment by rdmorin** [comment]
I also agree but really want to see it in the documentation. I am also strongly supportive of improving it (as per Bruno's suggestion) for compatibility with the increase of memory request over N attempts. If that works, we should shift to that approach across the board.

**Comment by Kdreval** [comment]
I am going to update the read the docs and will mention section on resource unpacking. Assigning this to myself for tracking purposes
