### ISSUE TITLE
PR template - I have some suggestions

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#95]
Is there some way I can edit the pull request template to be a bit more helpful and to provide guidance for version increases vs bug fixes?

**Comment by lkhilton** [comment]
The PR template is located in `.github/PULL_REQUEST_TEMPLATE.md` and can be edited on any branch. This is pretty out of date now, do you remember what you wanted to add?

**Comment by rdmorin** [comment]
Yes. It was mostly surrounding documentation of the process for increasing the version number, which wasn't documented anywhere at the time (and may still not be). I was also mulling over asking developers to add in-line comments explaining non-trivial and even what they might consider trivial changes with in-line comments. These could be deleted during a final set of commits but would help guide any reviewers to the rationale for changes that are not self-explanatory. Interested in your thoughts on this as a reviewer of many PRs.

**Comment by Kdreval** [comment]
Assigning this to myself for tracking. Will be added as section to readme
